apiVersion: v1
kind: Pod
metadata:
  labels:
    run: {{ .Release.Name }}
  name: {{ .Release.Name }}
spec:
  containers:
  - image: {{ .Values.image }}
    name: {{ .Release.Name }}
    env:
    - name: FIRST
      value: {{ .Values.var1 }}
    - name: SECOND
      value: {{ .Values.var2 }}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
